### ISSUE TITLE
dict key 'routes' does not exist

### ISSUE THREAD

**Issue by mohclips** [mohclips/k5-ansible-modules#17]
https://github.com/mohclips/k5-ansible-modules/blob/a75f8224a71b096e311390d5c97a415231ffdec6/k5_update_router_ports.py#L237

**Comment by mohclips** [comment]
```
            #if k5_debug:
            #    module.exit_json(changed=True, msg="Router ports Update Successful", k5_router_facts=response.json(), debug=k5_debug_out )


        else:
            module.fail_json(msg="port is not found for {}".format(port))

    #module.exit_json(changed=True, msg="Router ports Update Successful", k5_router_facts=response.json()['router'])
    if k5_debug:
        module.exit_json(changed=True, msg="Router ports Update Successful", k5_router_facts=response.json(), debug=k5_debug_out )
    else:
        module.exit_json(changed=True, msg="Router ports Update Successful", k5_router_facts=response.json())

    # no 'router' key in returned json

```
