### ISSUE TITLE
k5_auth - direct username / password combo fails after Apr 2017 update

### ISSUE THREAD

**Issue by mohclips** [mohclips/k5-ansible-modules#21]
`Auth plugin requires parameters which were not given: auth_url`

Tracked down to the os_client_config modules used in https://github.com/mohclips/k5-ansible-modules/blob/master/k5_auth.py#L221

This fails:
```
- name: Authenticate with K5 using k5_auth
    k5_auth:
      username: "{{ username }}"
      password: "{{ password }}"
      project_id: "{{ project_id }}"
      user_domain: "{{ user_domain_name }}"
      region_name: "{{ region.name }}"
    register: k5_auth_reg
```
