### ISSUE TITLE
k5_server_group - multiple same-name groups created

### ISSUE THREAD

**Issue by andyeff** [mohclips/k5-ansible-modules#30]
What looks like a quirk with K5 Openstack means that multiple server groups can be created with the same name.

My example uses four servers, two in AZ1 and two in AZ2. I group these in the inventory and have the following in a group_var:
```
---
server_group:
   name: "NPR-SMG-Affinity-Group-{{ az_suffix }}"
   policy: "anti-affinity"
```
The az_suffix is picked out of pre-defined "uk-1a" and "uk-1b" variables.

This is in turn used by a task in a build-server role to do the following:
```
- name: Create servergroups if required
  k5_server_group:
    state: present
    k5_auth: "{{ k5_auth_reg.k5_auth_facts }}"
    name: "{{ server_group.name }}"
    availability_zone: "{{ az }}"
    policies: "{{ server_group.policy }}"
  register: af_group
  when:  server_group is defined
  delegate_to: localhost
```

I would therefore expect when running a playbook that utilises this to create one server group per AZ, however when running a playbook the following is observed:

Output from Ansible Tower:
```
TASK [k5_buildvm : Create servergroups if required] ****************************
changed: [kpppsmg001 -> localhost]
changed: [kpppsmg003 -> localhost]
changed: [kpppsmg002 -> localhost]
changed: [kpppsmg004 -> localhost]
```

Output from Openstack 'server group list'
```
+--------------------------------------+--------------------------------+---------------+
| ID                                   | Name                           | Policies      |
+--------------------------------------+--------------------------------+---------------+
| d0ef9abf-efaa-4af1-b700-5b9f1bb56fd5 | NPR-SMG-Affinity-Group-az1     | anti-affinity |
| 5c98d9af-eecf-4c3e-9449-dd27c0d3a8c3 | NPR-SMG-Affinity-Group-az1     | anti-affinity |
| c6e582c9-b233-41b0-bff6-0645bec04cb4 | NPR-SMG-Affinity-Group-az2     | anti-affinity |
| 2dcf9347-200a-40bc-a91c-fa2c16add80b | NPR-SMG-Affinity-Group-az2     | anti-affinity |
+--------------------------------------+--------------------------------+---------------+
```
Each server is placed inside its own unique server group, instead of the desired outcome of two servers in their own matching AZ group.

 I suppose this might be an unsolvable problem due to Openstack not treating the server group names as unique and allowing multiple ID's to share the same name, but I felt like raising it as an issue to see if there's anything that can be done around this.
